name: judge_prediction
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy==1.26.4
  - pandas==2.2.2
  - seaborn==0.13.2
  - xgboost==2.1.1
  - statsmodels==0.14.2
  - tqdm==4.66.5
  - matplotlib==3.9.1
  - joblib==1.4.2
  - scikit-learn==1.5.1
  - scipy=1.13.1
  - shap==0.46.0